### ISSUE TITLE
Duplicate key in JSON

### ISSUE THREAD

**Issue by larsnaesbye** [gwbres/rinex#37]
In https://github.com/gwbres/rinex/blob/main/rinex/db/NAV/navigation.json#L123-L126 it seems like the same key `uraiNed`is present twice.

**Comment by gwbres** [comment]
Hello @larsnaesbye 

> In https://github.com/gwbres/rinex/blob/main/rinex/db/NAV/navigation.json#L123-L126 it seems like the same key `uraiNed`is present twice.

indeed, the last one should be named `uraiNed2` as indicated on page 74 of RINEX4 specifications.
[Fixed by latest commit](https://github.com/gwbres/rinex/commit/36095daf3113cba626291894dfa9b86f371f9f32)
Good catch
