### ISSUE TITLE
Automatic build of executables upon release?

### ISSUE THREAD

**Issue by larsnaesbye** [gwbres/rinex#43]
I noticed that some repos have automatically built binaries upon release. In our case I guess this would be the `rinex-cli`, `crx2rnx`, and `rnx2crx` binaries.

[This Github Action](https://github.com/marketplace/actions/rust-release-binary#build-windows-linux-and-mac-with-native-zip-types) might be able to do this. People can then check out the executables without having to install the full Rust toolset.

**Comment by larsnaesbye** [comment]
Currently awaiting https://github.com/rust-build/rust-build.action/pull/54

**Comment by gwbres** [comment]
Thank you was not aware of that, it is a very nice feature.
For instance, I have friends & colleagues not interested in moving to Rust, so not interested in the library itself, but certainly interested in using the applications we already have. This is something i will deploy ASAP

**Comment by larsnaesbye** [comment]
Oh yes, putting the tools into an organisation might make sense. Perhaps this is the start of a full IGS format toolbox ;-)

**Comment by larsnaesbye** [comment]
If we cannot get an update to Rust 1.61+, I can perhaps fork the above build action. Such a build action customised to our need could then live in the organisation.

**Comment by gwbres** [comment]
Hello,

let's move to email conversations, contact me at "guillaume dot bressaix at gmail dot com", that will be much easier.
All I can say is I don't foresee my other organizations hosting this subject, they are dedicated to oscillators characterization and that would be off topic

**Comment by larsnaesbye** [comment]
The build action has been updated, and in any case it's possible to set TOOLCHAIN to `stable`to get the latest Rust.

**Comment by larsnaesbye** [comment]
I have tried it out at https://github.com/larsnaesbye/Tempus_port/releases/tag/yatest for a completely unrelated test project. It seems to work, except I need to tweak it more to get Linux builds. I would also like to make macOS ARM builds if possible.

**Comment by gwbres** [comment]
Hello @larsnaesbye 

> I have tried it out at https://github.com/larsnaesbye/Tempus_port/releases/tag/yatest for a completely unrelated test project. It seems to work, except I need to tweak it more to get Linux builds. I would also like to make macOS ARM builds if possible.

I'm defintely more advanced in Gitlab than Github so I cannot help you much. 
But I found [this one](https://github.com/marketplace/actions/arm-none-eabi-gcc-gnu-arm-embedded-toolchain) and [that one](https://github.com/ARM-software/LLVM-embedded-toolchain-for-Arm) for ARM, and [Mac OS](https://rhonabwy.com/2020/05/09/continuous-integration-with-github-actions-for-macos-and-ios-projects/) seems to work "right away"

**Comment by larsnaesbye** [comment]
Great that you found other ways to build for Linux than the `musl` architecture!
