### ISSUE TITLE
orbits.json GPS CNAV typos

### ISSUE THREAD

**Issue by ljbade** [gwbres/rinex#79]
In the [`orbits.json`](https://github.com/gwbres/rinex/blob/main/rinex/db/NAV/orbits.json) file there are a few typos I spotted:

Under the GPS RINEX 4 section (actually seems to be for CNAV):
- `deltaNoDot` -> `deltaNDot`
- `uraiNed` -> `uraiEd` (note this is different to the `uraiNed0`/`uraiNed1`/`uraiNed2` fields which are correct
- `iscL1C` -> `iscL2C`
- `iscL1Cd` and `iscL1cCp` should be deleted - don't exist for CNAV, but do for CNV2 (so add back when https://github.com/gwbres/rinex/issues/78 implemented)

**Comment by larsnaesbye** [comment]
So, the first three can be replaced without negative effects, I guess? I'll make a PR.

**Comment by gwbres** [comment]
> So, the first three can be replaced without negative effects, I guess? I'll make a PR.

Nope, other than the dictionnary fields will eventually get renamed
